# ndarray 초기화 방법들

In [1]:
import numpy as np
#np.zeros(shape=(a,b)) 혹은 np.zeros((a,b)) 모든 값이 0인 a X b 크기의 배열 생성 
# -> 초기화

a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [2]:
#np.ones(shape=(a,b)) 혹은 np.ones((a,b)) 모든 값이 1인 a X b 크기의 배열 생성 

b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
#np.full(shape=(a,b),fill_value=c) 혹은 np.full((a,b),c) 모든 값이 c인 a X b 크기의
#배열 생성 
c = np.full((2,3),3)
c

array([[3, 3, 3],
       [3, 3, 3]])

In [7]:
# np.eye(a) 대각선 값은 1이고 나머지는 0인 a x a 크기의 2차원 배열 생성
# 만약 np.eye(a, b)인 경우 a x b 크기의 2차원 배열 생성
a = np.eye(5)
a


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
b = np.eye(2,3)
b

array([[1., 0., 0.],
       [0., 1., 0.]])

In [9]:
# np.random.randn(a, b) 임의의 값으로 채워진 a x b 크기의 배열 생성
np.random.randn(3,5)

array([[ 0.72168747,  0.73524248,  0.71831341, -0.1616778 , -1.70829395],
       [-0.80684446, -0.47889892, -0.77510285, -0.06946824, -0.83923998],
       [ 0.05446733,  1.34545527,  0.70683356, -0.2682833 , -0.4392017 ]])

# 슬라이싱(slicing)

In [10]:
a = np.array([1,2,3])
b = a[0:2]
b

array([1, 2])

In [11]:
a = np.array([[1,2,3],[4,5,6]])
b = a[0:2,0:2]
b

array([[1, 2],
       [4, 5]])

# Numpy 연산

In [20]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[4,1,5],[6,6,8]]) #동일한 인덱스에 위치한 요소끼리 사칙연산가능
c = a+b
c


array([[ 5,  3,  8],
       [10, 11, 14]])

In [21]:
d = a-b
d

array([[-3,  1, -2],
       [-2, -1, -2]])

# numpy array는 numpy array끼리 사칙연산이 가능하지만 Python list는 덧셈만 가능 -> 리스트로 합쳐짐
numpy array + numpy array 
–    같은 인덱스에 있는 값들끼리 더해짐
–    Ex. [1, 2, 3, 4, 5] + [1, 3, 5, 7, 9] →  [2, 5, 8, 11, 14] 
•     list + list
–    두 리스트의 값들이 한 리스트로 합쳐짐(concatenation)
–    Ex. [1, 2, 3, 4, 5] + [1, 3, 5, 7, 9] →  [1, 2, 3, 4, 5, 1, 3, 5, 7, 9
# numpy array는 numpy array끼리 뺄셈, 곱셈, 나눗셈 가능

# Numpy array는  array 전체에  연산이  가능하지만 Python list는  곱셈만  가능
numpy array + 5
–    array 안에 들어있는 각 값에 +5 –    Ex. [1, 2, 3] + 5 →  [6, 7, 8]
Python list는 곱셈만 가능
[1, 2, 3] * 3 →  [1, 2, 3, 1, 2, 3, 1, 2, 3]

•      결론
–    python list →  값을 추가하고 제거할 때 사용
–    numpy array →  수치 계산이 많고 복잡할 때 혹은 행렬 같은 다차원 배열을 쓸 때 사용