In [1]:
import numpy as np

a = np.array([1,2,3,4,5])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [3]:
import numpy as np # 2차원 배열 생성하기

b = np.array([[1,2,3],[4,5,6]])
print(type(b))
print(b)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [5]:
print(a.ndim) #1차원
print(a.shape) # 크기 5
print(b.ndim) #2차원
print(b.shape) #2X3 크기의 배열

1
(5,)
2
(2, 3)


In [3]:
import numpy as np
c = np.array([1,2,3,4,5])
d = np.array([[1,2,3],[4,5,6]])
print(c.ndim)
print(c.shape)
print(d.ndim)
print(d.shape)

1
(5,)
2
(2, 3)
