# 데이터사이언스 (0010085001)

## Exercise 3: Libraries for Data Science (NumPy)

In this excercise, we will cover NumPy library

### Array creation routines
* Ones and zeros

In [ ]:
import numpy as np

In [ ]:
# Create an 2-by-2 array of all zeros 
a = np.zeros((2,2), dtype=np.int8)
print(a)

[[0 0]
 [0 0]]


In [ ]:
# Create an 2-by-2 array of all ones 
a = np.ones((2,2))
print(a)

[[1. 1.]
 [1. 1.]]


In [ ]:
# Create an 2-by-2 array with random numbers
a = np.random.random((2,2))
a = np.random.rand(2, 2)
print(a)

print(np.__version__)

[[0.88048091 0.97487317]
 [0.04002657 0.48501097]]
1.22.4


In [ ]:
# Create an 1-by-6 array with elements 1 to 6
a = np.array([1, 2, 3, 4, 5, 6])
a = np.arange(1, 7)
print(a)

[1 2 3 4 5 6]


In [ ]:
# Create a two rows array with elements 1 to 6
b = np.array([[1,2,3],[4,5,6]])
b = np.arange(1, 7).reshape((2, 3))
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Print shape of the array
print(b.shape)

(2, 3)


In [ ]:
#  Create an array of zeros with the same shape and type as b
c = np.zeros_like(b)
print(c)

[[0 0 0]
 [0 0 0]]


In [ ]:
# Create an array of ones with the same shape and type as b
d = np.ones_like(b)
print(d)

[[1 1 1]
 [1 1 1]]


In [ ]:
# Create a new array of 2*5 uints, filled with 6.
# Use np.full() and np.ones()
a = np.full((2, 5), 6)
print(a)

b = np.ones([2, 5], dtype=np.int64) * 6
print(b)

[[6 6 6 6 6]
 [6 6 6 6 6]]
[[6 6 6 6 6]
 [6 6 6 6 6]]


### Array from existing data

In [ ]:
# Create an array of [1, 2, 3]
a = np.array([1, 2, 3])
a = np.arange(1, 4)
print(a)

[1 2 3]


In [ ]:
# Let x = [1, 2]. Convert it into an array (asarray)
x = [1, 2]
x = np.asarray(x)
print(x)

[1 2]


In [ ]:
# Let x = np.array([[1, 2], [3, 4]]). Convert it into a matrix (asmatrix)
x = np.array([[1, 2], [3, 4]])
x = np.asmatrix(x)
print(x)

[[1 2]
 [3 4]]


In [ ]:
# Let x = [1, 2]. Convert it into an array of float (asfarray)
x = [1., 2.]
x = np.asfarray(x)
print(x)
print(type(x[0]))

y = np.asarray(x, dtype=float)
print(y)
print(type(y[0]))

[1. 2.]
<class 'numpy.float64'>
[1. 2.]
<class 'numpy.float64'>


In [ ]:
# Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30
x = np.array([30])
# x = np.asscalar(x)
x = x.item()
print(x)

30


In [ ]:
# Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x
x = np.array([1, 2, 3])
y = np.copy(x)
print(id(x), x)
print(id(y), y)

140114972566224 [1 2 3]
140114972567856 [1 2 3]


### Array indexing
Since arrays may be multidimensional, you must specify a slice for each dimension of the array

In [ ]:
# Create an 3-by-4 array with elements 1 to 12
a = np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [ ]:
# From an array, print all rows which sum up to less or equal two
x = np.array([[0, 1], [1, 1], [2, 2]])
print(x)

rowsum = x.sum(-1)
print(rowsum)
print(x[rowsum <= 2, :])

[[0 1]
 [1 1]
 [2 2]]
[1 2 4]
[[0 1]
 [1 1]]


### Array math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module

In [ ]:
#############################################################
# General Usage
#############################################################
x = np.array([[1,2],
              [3,4]], dtype=np.float64)
y = np.array([[5,6],
              [7,8]], dtype=np.float64)

# Elementwise product of x and y
z = x * y
print(z)

[[ 5. 12.]
 [21. 32.]]


In [ ]:
# Matrix product of x and y
z = np.dot(x, y)
print(z)

[[19. 22.]
 [43. 50.]]


In [ ]:
# Compute sum of all elements in x
z = np.sum(x)
print(z)

10.0


In [ ]:
# Compute sum of each column in x;
z = np.sum(x, axis=0)
print(z)

[4. 6.]


In [ ]:
# Compute sum of each row in x
z = np.sum(x, axis=1)
print(z)

[3. 7.]


In [ ]:
#############################################################
# Broadcasting
#############################################################

# a 4 x 3
# b 1 x 3
a = np.array([[0.0, 0.0, 0.0,],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])

b = np.array([1.0, 2.0, 3.0])

print(a+b)

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [ ]:
x = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9], 
              [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) 

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
# Add the vector v to each row of the matrix x with stacking v multiple times (tile)
vv = np.tile(v, (4, 1))
print(vv)

y = x + vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
# Add the vector v to each row of the matrix x with broadcasting
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
# Multiply matrix x by a constant 2:
z = x * 2
print(z)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]


### Numpy Array as Data

* Data type: scalar, vector, matrix, tensor, and so on


In [ ]:
# Feature vector example 1

from sklearn.datasets import load_iris

iris = load_iris() 
print(iris.data[0, :])

In [ ]:
# Feature vector example 2
import matplotlib.pyplot as plt

from sklearn.datasets import load_digits 
digits = load_digits()  # 데이터 로드
samples = [0, 10, 20, 30, 1, 11, 21, 31]  # 선택된 이미지 번호
d = []
for i in range(8):
    d.append(digits.images[samples[i]])

plt.figure(figsize=(8, 2))
for i in range(8):
    plt.subplot(1, 8, i + 1)
    plt.imshow(d[i], interpolation='nearest', cmap=plt.cm.bone_r)
    plt.grid(False); plt.xticks([]); plt.yticks([])
    plt.title("image {}".format(i + 1))
plt.suptitle("숫자 0과 1 이미지")
plt.tight_layout()
plt.show()

In [ ]:
v = []
for i in range(8):
    v.append(d[i].reshape(64, 1))  # 벡터화
    
plt.figure(figsize=(8, 3))
for i in range(8):
    plt.subplot(1, 8, i + 1)
    plt.imshow(v[i], aspect=0.4,
               interpolation='nearest', cmap=plt.cm.bone_r)
    plt.grid(False); plt.xticks([]); plt.yticks([])
    plt.title("벡터 {}".format(i + 1))
plt.suptitle("벡터화된 이미지", y=1.05)
plt.tight_layout(w_pad=7)
plt.show()

### Image processing with Python, NumPy

In [ ]:
from PIL import Image # Python Imaging Library
import numpy as np
import scipy.misc


# How to read an image file as ndarray
image_url = "https://github.com/nkmk/python-snippets/blob/1dd9bd0b89a4465af229cbbfc2a1f8e3cb26d78c/notebook/data/src/lena.jpg"

# Download image and move it to the file (see left categories)
im = Image.open('./lena.jpg')
print(type(im))

# Convert Image to numpy.ndarray
im = np.array(im)

print(im.shape)
print(im.dtype)
print(im.shape)

<class 'PIL.JpegImagePlugin.JpegImageFile'>
(225, 400, 3)
uint8
(225, 400, 3)


In [ ]:
# Convert image to grayscale
# PIL.Image -> np.array
im_gray = np.array(Image.open('./lena.jpg').convert('L'))
print(im_gray.shape)

pil_img = Image.fromarray(im_gray) # np.array -> PIL.Image
pil_img.save('./lena_gray.jpg')

(225, 400)


In [ ]:
# Change the value of the element (pixel)
print(im.flags.writeable)

print(im[0, 0, 0])

im[0, 0, 0] = 0

print(im[0, 0, 0])

True
109
0


In [ ]:
# Generation of single color image and concatenation
image_url = "https://github.com/nkmk/python-snippets/blob/1dd9bd0b89a4465af229cbbfc2a1f8e3cb26d78c/notebook/data/src/lena_square.png?raw=true"

im = Image.open('./lena_square.jpg')
im = np.array(im)


# Make green and blue channel values to zero
im_R = im.copy()
im_R[:, :, (1, 2)] = 0

# Make red and blue channel values to zero
im_G = im.copy()
im_G[:, :, (0, 2)] = 0

# Make red and green channel values to zero
im_B = im.copy()
im_B[:, :, (0, 1)] = 0

# Concatenate each images along the axis 1
im_RGB = np.concatenate((im_R, im_G, im_B), axis=1)
# im_RGB = np.hstack((im_R, im_G, im_B))
# im_RGB = np.c_['1', im_R, im_G, im_B]

# Save image
pil_img = Image.fromarray(im_RGB)
pil_img.save('./lena_numpy_split_color.jpg')


In [ ]:
# Negative-positive inversion (invert pixel value)
im = np.array(Image.open('./lena_square.jpg').resize((256, 256)))

im_i = 255 - im

Image.fromarray(im_i).save('./lena_numpy_inverse.jpg')

In [ ]:
# Color reduction
im = np.array(Image.open('./lena_square.jpg').resize((256, 256)))

im_32 = im // 32 * 32
im_128 = im // 128 * 128

im_dec = np.concatenate((im, im_32, im_128), axis=1)

Image.fromarray(im_dec).save('./lena_numpy_dec_color.jpg')

In [ ]:
# Trimming with slice
m = np.array(Image.open('./lena_square.jpg'))
print(im.shape)

im_trim1 = im[128:384, 128:384]
print(im_trim1.shape)

Image.fromarray(im_trim1).save('./lena_numpy_trim.jpg')

(256, 256, 3)
(128, 128, 3)
